server:
  port: 8080

spring:
  application:
    name: security-gateway

  webflux:
    codecs:
      max-in-memory-size: 1MB

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: upstream_service_route
              uri: http://localhost:8081
              predicates:
                - Path=/api/**

sqli-detection:
  enabled: true
  model-service-url: "http://localhost:8000"
  model-service-timeout-ms: 15000
  fail-open: true
  cache:
    ttl-seconds: 300
    max-size: 10000

  thresholds:
    block: 0.90
    monitor: 0.75

resilience4j.circuitbreaker:
  instances:
    modelService:
      registerHealthIndicator: true
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 20
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true